=== TapiocaAberta/repasse-server/repasse-server/src/main/webapp/raml/schemas/agregacao-jsonschema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "ano" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    } ,
    "mes" : {
      "type" : "string" ,
      "required" : false
    } ,
    "dadosagregados" : {
      "type" : "string" ,
      "required" : false
    } ,
    "municipio" : {
      "type" : "string" ,
      "required" : false
    } ,
    "tipoagregacao" : {
      "type" : "string" ,
      "required" : false
    } ,
    "estado" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== TapiocaAberta/repasse-server/transfgov-server/src/main/webapp/raml/examples/agregacao.json
{
  "ano" : [
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value"
  ] ,
  "mes" : "some value" ,
  "dadosagregados" : "some value" ,
  "municipio" : "some value" ,
  "tipoagregacao" : "some value" ,
  "estado" : "some value"
}
