=== TapiocaAberta/repasse-server/transfgov-server/src/main/webapp/raml/schemas/municipio-jsonschema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    } ,
    "latitute" : {
      "type" : "string" ,
      "required" : false
    } ,
    "longitude" : {
      "type" : "string" ,
      "required" : false
    } ,
    "codigosiafi" : {
      "type" : "string" ,
      "required" : false
    } ,
    "estado" : {
      "type" : "string" ,
      "required" : false
    } ,
    "nome" : {
      "type" : "string" ,
      "required" : false
    } ,
    "regiao" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== TapiocaAberta/repasse-server/repasse-server/src/main/webapp/raml/examples/municipio.json
{
  "nome" : "some value" ,
  "regiao" : "some value" ,
  "estado" : "some value" ,
  "latitute" : "some value" ,
  "longitude" : "some value" ,
  "codigosiafi" : "some value" ,
  "id" : [
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value" ,
    "some value"
  ]
}
